### ISSUE TITLE
Sortering efter målestok giver sjove resultater

### ISSUE THREAD

**Issue by david-vinje** [SDFIdk/Arkivmeta_public#1]
Som om det sorterer alfabetisk i stedet for numerisk ... 

Resultatet af følgende API-kald "https://api.dataforsyningen.dk/arkivmeta/kort/?sort=maalestok&direction=asc&token=" er vist forneden.

![Udklip](https://user-images.githubusercontent.com/91406860/212875058-1c8dbbe5-6792-4d27-b396-15b3b19a661c.PNG)

**Comment by seskildsen** [comment]
Burde være fikset, men slå nok først igennem i morgen eller om et par dage.

**Comment by seskildsen** [comment]
Dog glemte jeg, at det kun er implementeret på version 2.0.0.

**Comment by david-vinje** [comment]
Den viser stadig målestok såsom 1000 og 10000 inden, den viser 200 og 400 selvom, de findes.

**Comment by david-vinje** [comment]
Den viser stadig målestok såsom 1000 og 10000, inden den viser 200 og 400, selvom de findes.

**Comment by david-vinje** [comment]
https://api.dataforsyningen.dk/arkivmeta_test/v2.0/kort?maalestok=1:200,1:1000,1:2000&sort=maalestok&token=

**Comment by seskildsen** [comment]
@david-vinje 

Nu skulle sorteringen på maalestok under `https://api.dataforsyningen.dk/rest/arkivmeta_test/v2.0/kort?sort=maalestok&token=` være sorteret alfabetisk (natural sort).
